export const features = {
  'trip-plans': {
    title: 'AI Trip Planner',
    description: 'Generate day-by-day trip plans with budgets and activities',
    icon: '✈️',
    endpoint: '/api/trip-plans',
    aiField: 'ai_plan',
    nameField: 'destination',
    columns: ['destination', 'duration_days', 'budget', 'travel_style', 'status'],
    columnLabels: { destination: 'Destination', duration_days: 'Days', budget: 'Budget', travel_style: 'Style', status: 'Status' },
    fields: [
      { name: 'destination', label: 'Destination', type: 'text', required: true },
      { name: 'duration_days', label: 'Duration (Days)', type: 'number', required: true },
      { name: 'budget', label: 'Budget ($)', type: 'number' },
      { name: 'travel_style', label: 'Travel Style', type: 'select', options: ['Cultural', 'Adventure', 'Relaxation', 'Luxury', 'Budget', 'Romantic', 'Urban Explorer'] },
      { name: 'interests', label: 'Interests', type: 'textarea' },
    ],
    formatValue: (col, val) => col === 'budget' ? `$${Number(val).toLocaleString()}` : val,
  },
  'content-items': {
    title: 'AI Content Generator',
    description: 'Create blog posts, articles, guides, and more with AI',
    icon: '📝',
    endpoint: '/api/content-items',
    aiField: 'generated_content',
    nameField: 'title',
    columns: ['title', 'content_type', 'topic', 'tone', 'status'],
    columnLabels: { title: 'Title', content_type: 'Type', topic: 'Topic', tone: 'Tone', status: 'Status' },
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'content_type', label: 'Content Type', type: 'select', options: ['Blog Post', 'Article', 'Whitepaper', 'Tutorial', 'Guide', 'Newsletter'] },
      { name: 'topic', label: 'Topic', type: 'text' },
      { name: 'tone', label: 'Tone', type: 'select', options: ['Professional', 'Informative', 'Friendly', 'Technical', 'Educational', 'Conversational', 'Creative'] },
    ],
  },
  'code-snippets': {
    title: 'AI Code Assistant',
    description: 'Generate code snippets with AI explanations',
    icon: '💻',
    endpoint: '/api/code-snippets',
    aiField: 'ai_explanation',
    nameField: 'title',
    columns: ['title', 'language', 'description', 'status'],
    columnLabels: { title: 'Title', language: 'Language', description: 'Description', status: 'Status' },
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'language', label: 'Language', type: 'select', options: ['JavaScript', 'Python', 'TypeScript', 'Go', 'Rust', 'Java', 'SQL', 'CSS', 'Bash', 'YAML', 'GraphQL', 'Dockerfile'] },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'code', label: 'Code', type: 'textarea' },
    ],
  },
  'image-prompts': {
    title: 'AI Image Prompt Generator',
    description: 'Create detailed prompts for AI image generation',
    icon: '🎨',
    endpoint: '/api/image-prompts',
    aiField: 'generated_prompt',
    nameField: 'title',
    columns: ['title', 'style', 'subject', 'mood', 'status'],
    columnLabels: { title: 'Title', style: 'Style', subject: 'Subject', mood: 'Mood', status: 'Status' },
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'style', label: 'Style', type: 'select', options: ['Digital Art', 'Photography', 'Watercolor', 'Abstract', 'Sci-Fi', 'Fantasy', 'Anime', 'Pixel Art', 'Vector', 'Vintage'] },
      { name: 'subject', label: 'Subject', type: 'text' },
      { name: 'mood', label: 'Mood', type: 'select', options: ['Peaceful', 'Dynamic', 'Mysterious', 'Cozy', 'Vibrant', 'Ethereal', 'Nostalgic', 'Elegant'] },
    ],
  },
  'business-plans': {
    title: 'AI Business Plan Generator',
    description: 'Create comprehensive business plans with AI',
    icon: '📊',
    endpoint: '/api/business-plans',
    aiField: 'ai_plan',
    nameField: 'business_name',
    columns: ['business_name', 'industry', 'target_market', 'budget', 'status'],
    columnLabels: { business_name: 'Business', industry: 'Industry', target_market: 'Target Market', budget: 'Budget', status: 'Status' },
    fields: [
      { name: 'business_name', label: 'Business Name', type: 'text', required: true },
      { name: 'industry', label: 'Industry', type: 'text' },
      { name: 'target_market', label: 'Target Market', type: 'text' },
      { name: 'budget', label: 'Budget ($)', type: 'number' },
    ],
    formatValue: (col, val) => col === 'budget' ? `$${Number(val).toLocaleString()}` : val,
  },
  'email-templates': {
    title: 'AI Email Composer',
    description: 'Write professional emails with AI assistance',
    icon: '📧',
    endpoint: '/api/email-templates',
    aiField: 'generated_email',
    nameField: 'subject',
    columns: ['subject', 'email_type', 'recipient_type', 'tone', 'status'],
    columnLabels: { subject: 'Subject', email_type: 'Type', recipient_type: 'Recipient', tone: 'Tone', status: 'Status' },
    fields: [
      { name: 'subject', label: 'Subject', type: 'text', required: true },
      { name: 'email_type', label: 'Email Type', type: 'select', options: ['Onboarding', 'Newsletter', 'Promotional', 'Transactional', 'Reminder', 'Announcement', 'Survey', 'Outreach', 'Apology'] },
      { name: 'recipient_type', label: 'Recipient Type', type: 'text' },
      { name: 'tone', label: 'Tone', type: 'select', options: ['Warm', 'Professional', 'Exciting', 'Friendly', 'Formal', 'Urgent', 'Sincere'] },
    ],
  },
  'recipes': {
    title: 'AI Recipe Creator',
    description: 'Generate detailed recipes with AI-powered creativity',
    icon: '🍳',
    endpoint: '/api/recipes',
    aiField: 'ai_recipe',
    nameField: 'title',
    columns: ['title', 'cuisine', 'dietary_restrictions', 'difficulty', 'status'],
    columnLabels: { title: 'Title', cuisine: 'Cuisine', dietary_restrictions: 'Dietary', difficulty: 'Difficulty', status: 'Status' },
    fields: [
      { name: 'title', label: 'Recipe Title', type: 'text', required: true },
      { name: 'cuisine', label: 'Cuisine', type: 'select', options: ['Italian', 'Japanese', 'French', 'Mexican', 'Indian', 'Thai', 'Korean', 'Mediterranean', 'Chinese', 'Vietnamese'] },
      { name: 'dietary_restrictions', label: 'Dietary Restrictions', type: 'select', options: ['None', 'Vegetarian', 'Vegan', 'Gluten-free', 'Pescatarian', 'Halal', 'Keto', 'Dairy-free'] },
      { name: 'difficulty', label: 'Difficulty', type: 'select', options: ['Easy', 'Medium', 'Hard'] },
      { name: 'ingredients', label: 'Key Ingredients', type: 'textarea' },
    ],
  },
  'resumes': {
    title: 'AI Resume Builder',
    description: 'Build ATS-optimized resumes with AI',
    icon: '📄',
    endpoint: '/api/resumes',
    aiField: 'ai_resume',
    nameField: 'full_name',
    columns: ['full_name', 'job_title', 'experience_years', 'skills', 'status'],
    columnLabels: { full_name: 'Name', job_title: 'Job Title', experience_years: 'Years Exp', skills: 'Skills', status: 'Status' },
    fields: [
      { name: 'full_name', label: 'Full Name', type: 'text', required: true },
      { name: 'job_title', label: 'Target Job Title', type: 'text' },
      { name: 'experience_years', label: 'Years of Experience', type: 'number' },
      { name: 'skills', label: 'Key Skills', type: 'textarea' },
    ],
  },
  'marketing-copies': {
    title: 'AI Marketing Copy',
    description: 'Create compelling marketing copy for any platform',
    icon: '📢',
    endpoint: '/api/marketing-copies',
    aiField: 'ai_copy',
    nameField: 'product_name',
    columns: ['product_name', 'platform', 'target_audience', 'status'],
    columnLabels: { product_name: 'Product', platform: 'Platform', target_audience: 'Audience', status: 'Status' },
    fields: [
      { name: 'product_name', label: 'Product Name', type: 'text', required: true },
      { name: 'platform', label: 'Platform', type: 'select', options: ['Facebook', 'Instagram', 'Google Ads', 'LinkedIn', 'Twitter', 'TikTok', 'YouTube', 'Pinterest'] },
      { name: 'target_audience', label: 'Target Audience', type: 'text' },
      { name: 'key_features', label: 'Key Features', type: 'textarea' },
    ],
  },
  'stories': {
    title: 'AI Story Writer',
    description: 'Write creative stories with AI imagination',
    icon: '📚',
    endpoint: '/api/stories',
    aiField: 'ai_story',
    nameField: 'title',
    columns: ['title', 'genre', 'setting', 'status'],
    columnLabels: { title: 'Title', genre: 'Genre', setting: 'Setting', status: 'Status' },
    fields: [
      { name: 'title', label: 'Story Title', type: 'text', required: true },
      { name: 'genre', label: 'Genre', type: 'select', options: ['Sci-Fi', 'Fantasy', 'Mystery', 'Romance', 'Thriller', 'Horror', 'Historical Fiction', 'Literary Fiction', 'Cyberpunk', 'Comedy'] },
      { name: 'setting', label: 'Setting', type: 'text' },
      { name: 'characters', label: 'Characters', type: 'textarea' },
    ],
  },
  'translations': {
    title: 'AI Language Translator',
    description: 'Translate text between languages with AI precision',
    icon: '🌍',
    endpoint: '/api/translations',
    aiField: 'translated_text',
    nameField: 'title',
    columns: ['title', 'source_language', 'target_language', 'status'],
    columnLabels: { title: 'Title', source_language: 'From', target_language: 'To', status: 'Status' },
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'source_language', label: 'Source Language', type: 'select', options: ['English', 'Spanish', 'French', 'German', 'Japanese', 'Chinese', 'Korean', 'Arabic', 'Portuguese', 'Russian'] },
      { name: 'target_language', label: 'Target Language', type: 'select', options: ['English', 'Spanish', 'French', 'German', 'Japanese', 'Chinese', 'Korean', 'Arabic', 'Portuguese', 'Russian', 'Italian', 'Dutch', 'Swedish', 'Turkish', 'Hindi', 'Thai'] },
      { name: 'original_text', label: 'Text to Translate', type: 'textarea' },
    ],
  },
  'seo-items': {
    title: 'AI SEO Optimizer',
    description: 'Get AI-powered SEO recommendations',
    icon: '🔍',
    endpoint: '/api/seo-items',
    aiField: 'ai_suggestions',
    nameField: 'page_title',
    columns: ['page_title', 'url', 'industry', 'status'],
    columnLabels: { page_title: 'Page', url: 'URL', industry: 'Industry', status: 'Status' },
    fields: [
      { name: 'url', label: 'URL', type: 'text', required: true },
      { name: 'page_title', label: 'Page Title', type: 'text' },
      { name: 'industry', label: 'Industry', type: 'text' },
      { name: 'keywords', label: 'Current Keywords', type: 'textarea' },
    ],
  },
  'chat-scripts': {
    title: 'AI Chat Support Scripts',
    description: 'Create customer support scripts with AI',
    icon: '💬',
    endpoint: '/api/chat-scripts',
    aiField: 'ai_script',
    nameField: 'title',
    columns: ['title', 'scenario', 'industry', 'tone', 'status'],
    columnLabels: { title: 'Title', scenario: 'Scenario', industry: 'Industry', tone: 'Tone', status: 'Status' },
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'scenario', label: 'Scenario', type: 'text' },
      { name: 'industry', label: 'Industry', type: 'text' },
      { name: 'tone', label: 'Tone', type: 'select', options: ['Helpful', 'Patient', 'Empathetic', 'Professional', 'Enthusiastic', 'Calm', 'Welcoming', 'Persuasive'] },
    ],
  },
  'product-descriptions': {
    title: 'AI Product Description',
    description: 'Write compelling product descriptions with AI',
    icon: '🏷️',
    endpoint: '/api/product-descriptions',
    aiField: 'ai_description',
    nameField: 'product_name',
    columns: ['product_name', 'category', 'price', 'status'],
    columnLabels: { product_name: 'Product', category: 'Category', price: 'Price', status: 'Status' },
    fields: [
      { name: 'product_name', label: 'Product Name', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'features', label: 'Key Features', type: 'textarea' },
      { name: 'price', label: 'Price ($)', type: 'number' },
    ],
    formatValue: (col, val) => col === 'price' ? `$${Number(val).toFixed(2)}` : val,
  },
  'social-posts': {
    title: 'AI Social Media Post',
    description: 'Create platform-optimized social media posts',
    icon: '📱',
    endpoint: '/api/social-posts',
    aiField: 'ai_post',
    nameField: 'title',
    columns: ['title', 'platform', 'topic', 'status'],
    columnLabels: { title: 'Title', platform: 'Platform', topic: 'Topic', status: 'Status' },
    fields: [
      { name: 'title', label: 'Post Title', type: 'text', required: true },
      { name: 'platform', label: 'Platform', type: 'select', options: ['LinkedIn', 'Instagram', 'Twitter', 'Facebook', 'TikTok', 'YouTube', 'Pinterest'] },
      { name: 'topic', label: 'Topic', type: 'text' },
      { name: 'hashtags', label: 'Suggested Hashtags', type: 'text' },
    ],
  },
  'learning-paths': {
    title: 'AI Learning Path Generator',
    description: 'Create personalized learning paths with AI',
    icon: '🎓',
    endpoint: '/api/learning-paths',
    aiField: 'ai_path',
    nameField: 'title',
    columns: ['title', 'subject', 'skill_level', 'status'],
    columnLabels: { title: 'Title', subject: 'Subject', skill_level: 'Level', status: 'Status' },
    fields: [
      { name: 'title', label: 'Path Title', type: 'text', required: true },
      { name: 'subject', label: 'Subject', type: 'text' },
      { name: 'skill_level', label: 'Skill Level', type: 'select', options: ['Beginner', 'Intermediate', 'Advanced'] },
      { name: 'goal', label: 'Goal', type: 'textarea' },
    ],
  },
};

export const featureList = Object.entries(features).map(([key, val]) => ({
  key,
  ...val,
}));
