module.exports = {
  caseType:'reconciled_marketplace_order', initialState:'order_draft',
  states:['order_draft','availability_reserved','priced','payment_pending','payment_confirmed','fulfillment_assigned','in_progress','exception','fulfilled','refund_review','refunded','closed'],
  createRoles:['customer','staff'],
  assessmentRoles:['staff','manager','finance_reviewer'],
  auditRoles:['manager','finance_reviewer','auditor'],
  connectorRoles:['integration_operator','manager'],
  evidenceKinds:['availability_snapshot','inventory_reservation','price_tax_snapshot','order_manifest','payment_receipt','staff_assignment','delivery_receipt','exception_record','cancellation_record','refund_approval','refund_receipt','reconciliation_report'],
  requiredSignals:['inventoryVersion','priceVersion','taxVersion','availabilityStatus','paymentStatus','totalMinor','currency','policyVersion'],
  professionalBoundary:'The workflow records status and approvals but cannot charge, refund, reserve inventory, or promise fulfillment without verified partner receipts.',
  connectors:[
    {name:'payment',purpose:'payment/refund receipts'},
    {name:'tax',purpose:'effective tax calculation references'},
    {name:'inventory',purpose:'atomic reservation receipts'},
    {name:'scheduling',purpose:'staff/service slot reservation'},
    {name:'messaging',purpose:'customer delivery receipts'},
    {name:'accounting',purpose:'ledger reconciliation'},
    {name:'delivery',purpose:'fulfillment status'},
    {name:'partner',purpose:'partner acceptance receipts'},
  ],
  transitions:[
    {from:'order_draft',action:'reserve_availability',to:'availability_reserved',roles:['staff'],requiresEvidence:true},
    {from:'availability_reserved',action:'lock_price',to:'priced',roles:['staff'],requiresEvidence:true},
    {from:'priced',action:'request_payment',to:'payment_pending',roles:['staff'],requiresEvidence:true},
    {from:'payment_pending',action:'confirm_payment',to:'payment_confirmed',roles:['finance_reviewer'],requiresEvidence:true,dualControl:true},
    {from:'payment_confirmed',action:'assign_fulfillment',to:'fulfillment_assigned',roles:['manager'],requiresEvidence:true},
    {from:'fulfillment_assigned',action:'start',to:'in_progress',roles:['staff'],requiresEvidence:true},
    {from:'in_progress',action:'record_exception',to:'exception',roles:['staff','manager'],requiresEvidence:true},
    {from:'in_progress',action:'complete',to:'fulfilled',roles:['staff'],requiresEvidence:true,dualControl:true},
    {from:'exception',action:'request_refund',to:'refund_review',roles:['manager'],requiresEvidence:true},
    {from:'refund_review',action:'approve_refund',to:'refunded',roles:['finance_reviewer'],requiresEvidence:true,dualControl:true},
    {from:'fulfilled',action:'close',to:'closed',roles:['manager'],requiresEvidence:true,dualControl:true},
    {from:'refunded',action:'close',to:'closed',roles:['manager'],requiresEvidence:true,dualControl:true},
  ],
  assess:x=>{const total=Number(x.totalMinor);const valid=Number.isSafeInteger(total)&&total>=0&&/^[A-Z]{3}$/.test(x.currency);return{disposition:valid&&x.availabilityStatus==='reserved'&&x.paymentStatus==='verified_receipt'?'fulfillment_assignment_review_required':'availability_payment_or_price_hold',paymentCommand:null,totalMinor:valid?total:null,versions:{inventory:x.inventoryVersion,price:x.priceVersion,tax:x.taxVersion}};},
};
